### ISSUE TITLE
Upload pxd001819.txt

### ISSUE THREAD

**Issue by david-bouyssie** [wombat-p/Proline-Workflow#2]
In this section https://github.com/wombat-p/Proline-Workflow#run-benchmarking-data-set
we give this example of nextflow execution:

```
nextflow run main.nf --raws 'RAWFOLDER/*.raw' --fasta yeast_UPS.fasta --precursor_mass_tolerance 5 --fragment_mass_tolerance 0.8 --miscleavages 2 \
--variable_mods 'Oxidation of M, Acetylation of protein N-term' --experiment_design 'pxd001819.txt' --lfq_param \
'lfq_param_file.txt' --max_cpus 8 --max_memory 16GB -profile docker -with-report -with-trace -with-timeline
```

However there is no "pxd001819.txt" file in this repo.

We should thus upload a file named "pxd001819.txt" in the folder
https://github.com/wombat-p/Proline-Workflow/tree/dev/Nextflow/data

This file should contain the full experimental design.

This should help to understand/execute the provided example.

**Comment by veitveit** [comment]
The location of the files is now specified
" These files are given in the Results folder of this workflow: https://github.com/veitveit/IS_Benchmarking/tree/master/Proline/Results"

**Comment by david-bouyssie** [comment]
Currently the provided example do not load config files from the Results folder.
Don't you think we should provide an example that works out of the box after a ```git clone``` + one call to wget?
